data_processing:
  chunk_size: 100000
  gpu_memory_fraction: 0.8
  validation_threshold: 0.2
models:
  lstm:
    hidden_size: 50
    sequence_length: 30
  sarima:
    enabled: true
  tft:
    enabled: true
