feature_engineering:
  aggregations:
    functions:
    - mean
    - std
    - min
    - max
    - range
    - skew
    - kurt
  interaction_features:
  - - "TEMPERATURA DO AR - BULBO SECO HORARIA \xB0C"
    - UMIDADE RELATIVA DO AR HORARIA %
  - - PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO HORARIA MB
    - "TEMPERATURA DO AR - BULBO SECO HORARIA \xB0C"
  rolling_windows:
    long_term:
    - 720
    - 2160
    - 4320
    medium_term:
    - 168
    - 336
    - 504
    short_term:
    - 24
    - 48
    - 72
  seasonal_decomposition:
    extrapolate_trend: freq
    model: additive
    period: 24
  temporal_features:
    categorical:
    - season
    - is_weekend
    - is_holiday
    cyclical:
    - hour
    - day
    - month
    - day_of_week
    numerical:
    - day_of_year
    - week_of_year
gpu:
  allow_memory_growth: true
  batch_growth_rate: 1.5
  memory_fraction: 0.8
  memory_growth: true
  optimization:
    mixed_precision: true
    tensor_cores: true
    xla: true
  per_process_gpu_memory_fraction: 0.9
  precision: float32
models:
  lstm:
    architecture:
      bidirectional: true
      dropout: 0.1
      hidden_size: 128
      input_size: null
      num_layers: 2
    enabled: true
    training:
      batch_norm: true
      gradient_clip: 1.0
      layer_norm: true
      sequence_length: 168
      stride: 24
  sarima:
    enabled: true
    fitting:
      enforce_invertibility: true
      enforce_stationarity: true
      maxiter: 50
      method: lbfgs
      optim_score: aic
    order:
      d:
      - 0
      - 1
      p:
      - 0
      - 1
      - 2
      q:
      - 0
      - 1
      - 2
    seasonal_order:
      D:
      - 0
      - 1
      P:
      - 0
      - 1
      Q:
      - 0
      - 1
      s:
      - 24
      - 168
      - 720
  tft:
    architecture:
      attention_head_size: 4
      categorical_embedding_dim: 8
      dropout: 0.1
      hidden_continuous_size: 32
      hidden_size: 64
    enabled: true
    training:
      max_encoder_length: 720
      max_prediction_length: 168
      min_encoder_length: 168
output:
  base_dir: outputs
  forecast:
    confidence_intervals:
    - 0.1
    - 0.9
    frequency: H
    horizon: 87600
    include_history: true
  logging:
    date_format: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
  metrics:
    format: json
    include:
    - rmse
    - mae
    - mape
    - r2
    - coverage_rate
    - interval_score
  subdirs:
    logs: logs
    metrics: metrics
    models: models
    plots: plots
    predictions: predictions
  visualization:
    color_palette: deep
    context: paper
    dpi: 300
    figure_sizes:
      default:
      - 12
      - 8
      tall:
      - 10
      - 12
      wide:
      - 15
      - 8
    fonts:
      family: Arial
      size: 12
      title_size: 14
    formats:
    - png
    - html
    - svg
    style: classic
preprocessing:
  datetime_format: '%Y-%m-%d %H:%M:%S'
  invalid_values:
  - -9999.0
  - -999.0
  - -99.0
  - 9999.0
  missing_values:
    interpolation_limit: 24
    interpolation_methods:
      categorical: mode
      numeric: cubic
    strategy:
      long_gaps: seasonal_interpolate
      medium_gaps: interpolate
      short_gaps: forward_fill
  outlier_detection:
    method: zscore
    rolling_window: 720
    threshold: 3.0
  scaling:
    method: robust
    parameters:
      quantile_range:
      - 0.01
      - 0.99
  target_variable: "TEMPERATURA DO AR - BULBO SECO HORARIA \xB0C"
training:
  batch_size: 64
  cross_validation:
    n_splits: 5
    shuffle: false
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 0.001
  optimizer:
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1.0e-08
      weight_decay: 0.0001
    type: adam
  scheduler:
    parameters:
      factor: 0.5
      min_lr: 1.0e-06
      mode: min
      patience: 5
    type: reduce_on_plateau
  validation_split: 0.2
validation:
  cross_validation:
    gap: 24
    n_splits: 5
  data_quality:
    correlation_threshold: 0.95
    missing_threshold: 0.2
    variance_threshold: 0.01
  metrics_threshold:
    mae: 1.5
    mape: 10.0
    r2: 0.8
    rmse: 2.0
  test_size: 0.2
  validation_size: 0.1
